### ISSUE TITLE
Errors while trying to search

### ISSUE THREAD

**Issue by micouy** [brandon1024/find#315]
## Issue Description
I get errors in console after just trying out the extension. My browser is `Brave 1.3.118`. I have just installed the extension.

Errors:
```
Error in event handler: TypeError: Cannot read property 'childNodes' of null
    at Object.self.highlightAll (chrome-extension://<extension-id>/content/highlighter.js:69:31)
    at chrome-extension://<extension-id>/content/content.js:48:42
```

```
Error in event handler: TypeError: Cannot read property 'parentElement' of null
    at Object.self.restoreWebPage (chrome-extension://<extension-id>/content/parser.js:152:20)
    at chrome-extension://<extension-id>/content/content.js:38:37
```

```
Error in event handler: TypeError: Cannot read property 'nodeUUID' of undefined
    at Object.self.highlightAll (chrome-extension://<extension-id>/content/highlighter.js:162:63)
    at chrome-extension://<extension-id>/content/content.js:48:42
```

## Steps to Reproduce
- Go to [https://docs.rs/im/14.3.0/src/im/nodes/btree.rs.html#1224-1227](https://docs.rs/im/14.3.0/src/im/nodes/btree.rs.html#1224-1227) (on some sites the extension just works, on others it doesn't highlight anything, on some it shows errors)
- Open the extension, type `Update` or something

**Comment by brandon1024** [comment]
Interesting. The extension really doesn't like this page for some reason. I'll dig into this some more when I have some free time.

**Comment by brandon1024** [comment]
@micouy  I looked into this a bit further today. I originally thought that this was because the Rust docs pages were dynamic, but that doesn't seem to be the case. The Rust documentation seems to use a templating engine that is pretty heavy on the HTML markup. Specifically, it wraps bits of text in <span> elements for highlighting and indentation. The one you included in your ticket was particularly bad given how large the source file was; it was even difficult for me to show the HTML in the dev tools.

![image](https://user-images.githubusercontent.com/22732449/80926649-d785a380-8d6e-11ea-8cb7-252187f40c44.png)

My guess is that the extension is churning on the page and becomes unresponsive for a while. If you let the extension run on the page, the expression (sometimes) gets highlighted but it takes quite a while.

I have addressed the performance of the extension in a number of other issues, and I've optimized the extension as much as I reasonably can. At this juncture, I've decided that the extension simply won't support enormous DOMs or a large amount of data. It's a bummer, but my hands are tied.

In light of this though, I'm going to make a few changes to help report to the user when dynamic pages or strange errors are detected. These changes should come out soon.

Thanks for your patience!
