### ISSUE TITLE
Doesn't work in Brave browser

### ISSUE THREAD

**Issue by mblais** [brandon1024/find#412]
## Issue Description
Does not work in Brave browser.
[Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)](https://brave.com/latest/)

## Steps to Reproduce
- Try a search on any page

## Screenshots and Documentation
Console error:
_generated_background_page.html:1 Error in event handler: TypeError: Cannot read properties of null (reading 'length')
    at computeSubsequentIndex (chrome-extension://fddffkdncgkkdjobemgbpojjeffmmofb/background/background.js:420:40)
    at self.seekSearch (chrome-extension://fddffkdncgkkdjobemgbpojjeffmmofb/background/background.js:223:21)
    at actionDispatch (chrome-extension://fddffkdncgkkdjobemgbpojjeffmmofb/background/browser-action-proxy.js:62:33)
    at chrome-extension://fddffkdncgkkdjobemgbpojjeffmmofb/background/browser-action-proxy.js:28:17

**Comment by pzhlkj6612** [comment]
Reproducible, in any browsers.

You seemed to search things in Brave browser's internal pages or browser's web store. For example:

- chrome-extension://...
- brave://about/
- https://chromewebstore.google.com/category/extensions

Extensions cannot work on these webpages. We are working on showing warnings about more URLs in #418. 

In Firefox, the error message looks like this:

```
TypeError: can't access property "length", regexOccurrenceMap is null

```

.

**Comment by pzhlkj6612** [comment]
find+ | Regex Find-in-Page Tool - Chrome Web Store https://chromewebstore.google.com/detail/find%2B-regex-find-in-page/fddffkdncgkkdjobemgbpojjeffmmofb

Chrome extension v2.2.3 is there! Now the limited pages should be recognized, and warnings should be correctly displayed.
